# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  TargetRubyVersion: 2.5

  # Don't check binstubs or gemfile
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/*_helper.rb'
    - 'vendor/**/*'

Layout/EmptyLineAfterMagicComment:
  Enabled: false

# Allow braces for blocks that mainly return a value, including RSpec lets and
# subjects
Style/BlockDelimiters:
  EnforcedStyle: semantic

# Don't require a class comment
Style/Documentation:
  Enabled: false

# Require trailing commas for multiline arrays
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# Require trailing commas for multiline hashes
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Require trailing commas for multiline argument lists
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Allow but do not require modifier usage of if/unless
Style/IfUnlessModifier:
  Enabled: false

# Default Rails files have comment lines this long
Metrics/LineLength:
  Max: 120

# This is the style I saw in the Ruby world
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Allow *%i[…]
Lint/UnneededSplatExpansion:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false

# The examples I see always use stabby lambdas
Style/Lambda:
  Enabled: false

# casecmp().zero? is less readable, so I don't want to enforce it unless performance requires it
Performance/Casecmp:
  Enabled: false

# Single line {}, multiline do…end
Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Layout/EmptyLineAfterGuardClause:
  Enabled: false
